import { toast } from 'sonner'
import { readSSE } from '@/api/client'

/**
 * Runs one statement outside of any editor tab (grid edits, sidebar actions),
 * so the user's query is never overwritten. The statement is generated by the
 * app after an explicit user action, hence `force`.
 * Resolves to null on success, or to the error message (already shown as a toast).
 */
export async function runStatement(connectionId: string, sql: string): Promise<string | null> {
  let error: string | null = null
  let detail: string | undefined
  try {
    for await (const { event, data } of readSSE('/query', { connectionId, sql, limit: 1, force: true })) {
      if (event === 'error') {
        const d = data as { message?: string; detail?: string }
        error = d.message || 'Query execution failed'
        detail = d.detail
      } else if (event === '__http') {
        const b = (data as { body: Record<string, unknown> }).body
        error = String(b['message'] ?? b['title'] ?? 'Unknown error')
      }
    }
  } catch (err) {
    error = err instanceof Error ? err.message : String(err)
  }
  if (error) {
    const full = detail ? `${error}\n${detail}` : error
    toast.error(error, {
      ...(detail ? { description: detail } : {}),
      duration: Infinity,
      action: { label: 'Copy', onClick: () => void navigator.clipboard.writeText(full) },
    })
  }
  return error
}
